### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by eantones** [nuobit/lighting-vertical#26]
# Todo
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate
- [x] lighting - By @KNVx - #21
- [x] lighting_advanced_search - By @KNVx - #24
- [x] lighting_attachment_package - By @KNVx #39 
- [x] lighting_etim - By @KNVx - #31 
- [x] lighting_export - By @KNVx - #32 
- [x] lighting_export_json - By @KNVx #33
- [x] lighting_export_xlsx - By @KNVx #38 
- [x] lighting_portal - By @KNVx - #25
- [x] lighting_portal_connector - By @KNVx - #28
- [x] lighting_project - By @KNVx - #27 
- [x] lighting_reporting - By @KNVx - #22 
- [x] lighting_reporting_attachment - By @KNVx - #34
- [x] lighting_reporting_etim - New from lighting_reporting - By @KNVx - #22 
- [x] lighting_reporting_seo - New from lighting_reporting - By @KNVx - #22 
- [x] lighting_review - By @KNVx  - #35 
- [x] lighting_seo - By @KNVx - #23
- [ ] lighting_topbar -  By @KNVx - #40 
- [x] connector_ftp_attachment - By @KNVx - #41
- [x] connector_lighting_sapb1 - By @KNVx - #29

**Comment by eantones** [comment]
@KNVx
